name: My-proj
env:
  APPLICATION_NAME: 'MyFlask'
  DEPLOY_PACKAGE_NAME: 'Flask-deploy-ver-${{ github.sha }}'

on: 
  push:
    branches: 
      - main 

jobs: 
  my_testing:
    runs-on: ubuntu-latest

    steps: 
    - name: Print Hello Messege in Testing
      run: echo 'Hello World from testing job'

    - name: Execure few commands
      run:
        echo 'Hello Message1'
        echo 'Hello Message2'
        echo 'Application name ${{ env.APPLICATION_NAME }}'

  my_deploy:
    runs-on: ubuntu-latest

    needs: [my_testing]

    steps:
    - name: Print Hello Message in Deploy
      run: echo 'Hello World from Deploy job'
    - name: Printing Deploying packege
      run: echo 'Deploy packege name is ${{ env.DEPLOY_PACKAGE_NAME}}'
